# Tranquilpeak
# Version : 0.2.0-ALPHA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseurl = "http://blogs.singleye.net/"
appendPort = false
languageCode = "zh-cn"
title = "人在江湖飘..."
theme= "hugo-theme-geppaku"
disqusShortname = "singleye"
googleAnalytics = "UA-90087618-1"
paginate = 5
canonifyurls = true
defaultContentLanguage = "zh-cn"


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "singleye"

    # Please set account ids
    # This is Optional values
    # twitter  = "twitter id"
    # linkedin = "linkedin id"
    github   = "singleye"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = true
        # facebook = true
        # hatena   = true # hatena is Japanese social media
        google   = true
        # pocket   = true
        # Please set id when you want to display facebook
        # facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        # sidebar = "adsense/sidebar.html"
        # content = "adsense/content.html"
